### ISSUE TITLE
Plotly plots not showing on libretexts

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#193] opened 2020-10-05 03:55 UTC
From Yisang Luo:

> There are two python codes that use plotly package could not generate the plots. I have tested them on my laptop with the same > version of package, and they work fine. 
> https://chem.libretexts.org/Under_Construction/Sandboxes/schrodingers-snake/CHE30324-Hydrogen_3d.ipynb
> https://chem.libretexts.org/Under_Construction/Sandboxes/schrodingers-snake/CHE30324-3dbox.ipynb
> There are two python codes that use plotly package could not generate the plots. Specifically, they will output blank pages without any errors/warnings. I have tested them on my laptop with the same version of package, and they work fine.

**Comment by sandertyu** [comment] 2020-10-05 04:14
On LibreTexts, it eventually outputs for both plots but you just get a big white space;

![libretexts output](https://cdn.discordapp.com/attachments/387895582733369346/762527872833159178/unknown.png)

Similar behavior on JupyterHub;

![code on hub](https://cdn.discordapp.com/attachments/387895582733369346/762525240328585226/unknown.png)

This is also very odd. Plotly *is* available in our default-env 2.0, although it was not in our legacy image for some reason (you can confirm with `conda list | grep plotly`).

![no plotly](https://cdn.discordapp.com/attachments/387895582733369346/762527155664977930/unknown.png)

**Comment by moorepants** [comment] 2020-10-05 04:37
Maybe it isn't properly or fully installed on the hub?

**Comment by moorepants** [comment] 2020-10-05 15:19
This doesn't work locally for me either.
![image](https://user-images.githubusercontent.com/276007/95098205-aac72500-072e-11eb-9750-b8366fb1a611.png)
I recommend investigating the conda forge feedstock: https://github.com/conda-forge/plotly-feedstock, maybe this doesn't install things properly. This is how I installed plotly locally also. But plotly does work inside a dash app for me locally. Maybe something isn't installed to connect plotly to Jupyter.

**Comment by moorepants** [comment] 2020-10-05 15:19
Maybe clues here: https://github.com/plotly/plotly.py/issues/2508

**Comment by moorepants** [comment] 2020-10-06 08:13
This is likely this issue that needs to be solved: https://github.com/conda-forge/plotly-feedstock/issues/84

**Comment by moorepants** [comment] 2020-10-06 08:55
It may be that we need to install this: https://github.com/conda-forge/jupyterlab-plotly-extension-feedstock

**Comment by moorepants** [comment] 2020-10-06 08:58
I did "conda install jupyterlab-plotly-extension" on my computer and still get the same result.

**Comment by sandertyu** [comment] 2020-11-09 09:55
We fixed this on JupyterHub by instead adding the extension through PostBuild, but it looks like this still doesn't display any output on LibreTexts; 

![no-module-plotly](https://user-images.githubusercontent.com/59950537/98526288-6e577f00-222e-11eb-8293-21e6264b9a4b.png)

Plotly definitely does exist though, because simple `import plotly` then `print(1+1)` works. But no plots in general will display.

**Comment by Miniland1333** [comment] 2020-11-10 19:32
Confirmed: Conflict with Citationjs.js library. Blocking the script allows it to load properly. (https://files.libretexts.org/github/LibreTextsMain/Aryan%20Suri/Citation/citationjs.js).

Maybe this is another requirejs conflict?

![image](https://user-images.githubusercontent.com/12994749/98724248-4f4d1000-2348-11eb-9b2c-9a0fb7f5f3bf.png)

**Comment by moorepants** [comment] 2020-11-10 20:14
Is it possible to selectively block citation.js on libretexts pages that have thebe loaded, as a stop-gap?

**Comment by moorepants** [comment] 2020-11-10 20:15
Or what is the best path forward to fix this?

**Comment by sandertyu** [comment] 2020-11-11 00:33
> Or what is the best path forward to fix this?

Henry said that they would prefer not to turn the `citation.js` library off because they have other code which depends on it. However, they also suggested that we look for the components from that library which are being used, and then try and figure out which ones are causing the conflict. Hopefully it ends up being an unnecessary one and we can simply block that component.

**Comment by Miniland1333** [comment] 2020-11-11 04:53
I'm going to run this fix by my team first, but basically as you can see at the top of the [citationJS library](https://cdn.jsdelivr.net/npm/citation-js@0.4.0-7/build/citation.js
) that the library defines `require` with some sort of custom loader. This obviously caused namespace collisions and confused the requireJS code. To fix this as seen in LibreTexts/Libretext#97 I simply renamed all instances of require with CitRequire to separate out the namespaces.

Testing on (https://chem.libretexts.org/Under_Construction/Sandboxes/schrodingers-snake/CHE30324-Hydrogen_3d.ipynb) now indicates that the plotly continues to function and the Citation also functions. To check the Citation, it is left blue bar > Tools > Get Page Citation.
![image](https://user-images.githubusercontent.com/12994749/98770198-821df500-2396-11eb-8a9b-6c7ae056acd1.png)


Overall, the issue was the CitationJS library defining its own custom script loader, so I fixed it by renaming the custom loader. I think this will be a really good example of how to do JavaScript debugging in the browser. Once LibreTexts/Libretext#97 is merged, I will confirm that plotly remains fixed and this issue should automatically close.

**Comment by rkevin-arch** [comment] 2020-11-11 05:03
~~inb4 this fixes _all_ our issues about widgets working in a plain Thebe page but not on LibreTexts~~

**Comment by moorepants** [comment] 2020-11-17 19:28
This is now fixed!

**Comment by Miniland1333** [comment] 2020-11-17 19:30
Still waiting on LibreTexts/libretext#97 before this is fully resolved on all libraries. Currently, I have the hotfix running on just Chem since I need that PR merged before it hits deployment.

**Comment by Miniland1333** [comment] 2020-11-17 19:31
Note to future Henry: don't forget to update https://chem.libretexts.org/Template:Custom/Views/ContentHeader once LibreTexts/Libretext#97 is merged.

**Comment by moorepants** [comment] 2020-11-17 19:49
Ok. thanks for the update. I told Yisang that it was working on the chem library.

**Comment by Miniland1333** [comment] 2020-11-20 04:03
This has now been deployed through LibreTexts/Libretext#97 to all the LibreTexts libraries. Could you all confirm that https://files.libretexts.org/github/LibreTextsMain/Aryan%20Suri/Citation/citationjs.js appears to you to be the new version? You will know you are accessing the updated version if the file starts with `CitRequire` rather than `require`. If it does not appear to be updated on first visit, try to clear your browser cache using CTRL+F5 and see if it updates.

Hope to hear from you and to hopefully finally close this issue!

**Comment by celine168** [comment] 2020-11-20 19:25
Looks like it's using CitRequire, and the plot shows for me! There is an incompatible glossary error in the console, but it doesn't seem to affect the appearance of the plot.
![image](https://user-images.githubusercontent.com/22624020/99841389-f426d480-2b22-11eb-92a5-6c4073945a6d.png)

**Comment by celine168** [comment] 2020-11-24 18:19
I know @rkevin-arch mentioned to try this on another LibreTexts site, and it seems to also work on query.
![plotly](https://user-images.githubusercontent.com/22624020/100135183-1f206980-2e3e-11eb-90c9-8b17142a0634.PNG)
![plotly2](https://user-images.githubusercontent.com/22624020/100135190-2182c380-2e3e-11eb-8555-fcb88dcc2220.png)

I also did a runthrough of the other widgets that work on Thebe but not on LibreTexts, and they do not seem to be fixed by the renaming.

**Comment by sandertyu** [comment] 2020-11-25 22:48
Henry confirmed that this has been deployed to all libraries and everything looks good on our end. Closing.

**Closed by sandertyu** 2020-11-25 22:48 UTC
Labels: high priority, libretexts page integration
