### ISSUE TITLE
Investigate issue with chick7/10/13 where user are not able to spawn a notebook

### ISSUE THREAD

**Issue by narrator0** [LibreTexts/metalc#98] opened 2019-11-22 21:06 UTC

**Comment by narrator0** [comment] 2019-11-23 06:54
Known issue about the terminating pods. https://github.com/kubernetes/kubernetes/issues/84214

**Comment by lux12337** [comment] 2019-11-25 19:48
hub pod deleted itself:
kubectl describe the hub pod:
```
Name:                      hub-674dbcf9c7-5nkgx
Namespace:                 jhub
Priority:                  0
PriorityClassName:         <none>
Node:                      chick11/10.0.0.111
Start Time:                Fri, 22 Nov 2019 22:20:15 -0800
Labels:                    app=jupyterhub
                           component=hub
                           hub.jupyter.org/network-access-proxy-api=true
                           hub.jupyter.org/network-access-proxy-http=true
                           hub.jupyter.org/network-access-singleuser=true
                           pod-template-hash=674dbcf9c7
                           release=jhub
Annotations:               checksum/config-map: a96d52b55686eafe91e057af7e38272a924250893cfc6d0c0c7a0d15dc76d217
                           checksum/secret: 9b3b8ae6071bd519044579b015e71c35ebd9c9ec664c9dfe845c8898e7040057
                           cni.projectcalico.org/podIP: 10.244.58.34/32
Status:                    Terminating (lasts 18m)
Termination Grace Period:  30s
IP:                        10.244.58.34
Controlled By:             ReplicaSet/hub-674dbcf9c7
Init Containers:
  git-clone-templates:
    Container ID:  docker://6420bf054c79f6ec0e8f8b42d19ba1800efe1928f0385721c5bca2464d33ee03
    Image:         alpine/git
    Image ID:      docker-pullable://alpine/git@sha256:8f5659025d83a60e9d140123bb1b27f3c334578aef10d002da4e5848580f1a6c
    Port:          <none>
    Host Port:     <none>
    Args:
      clone
      --single-branch
      --branch=master
      --depth=1
      --
      https://github.com/LibreTexts/jupyterhub-templates.git
      /etc/jupyterhub/custom
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 22 Nov 2019 22:20:22 -0800
      Finished:     Fri, 22 Nov 2019 22:20:23 -0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/jupyterhub/custom from custom-templates (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hub-token-79zrt (ro)
  git-clone-images:
    Container ID:  docker://faf8f17d08c2434d11ffc94551f118aca204374e75cd0ce4e88848f1750de682
    Image:         alpine/git
    Image ID:      docker-pullable://alpine/git@sha256:8f5659025d83a60e9d140123bb1b27f3c334578aef10d002da4e5848580f1a6c
    Port:          <none>
    Host Port:     <none>
    Args:
      clone
      --single-branch
      --branch=master
      --depth=1
      --
      https://github.com/LibreTexts/jupyterhub-images.git
      /usr/local/share/jupyterhub/static/external
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 22 Nov 2019 22:20:25 -0800
      Finished:     Fri, 22 Nov 2019 22:20:27 -0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /usr/local/share/jupyterhub/static/external from custom-images (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hub-token-79zrt (ro)
Containers:
  hub:
    Container ID:  docker://747279b721319500205c11051269a600eee9f4ad9c380d23d4f830ca2617c398
    Image:         jupyterhub/k8s-hub:0.9-dcde99a
    Image ID:      docker-pullable://jupyterhub/k8s-hub@sha256:4cae028491282d7f1710e6342786e60b268cc0733f0a6a046873bed5d760bcc4
    Port:          8081/TCP
    Host Port:     0/TCP
    Command:
      jupyterhub
      --config
      /srv/jupyterhub_config.py
      --upgrade-db
    State:          Running
      Started:      Fri, 22 Nov 2019 22:20:29 -0800
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      200m
      memory:   512Mi
    Readiness:  http-get http://:hub/hub/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      PYTHONUNBUFFERED:        1
      HELM_RELEASE_NAME:       jhub
      POD_NAMESPACE:           jhub (v1:metadata.namespace)
      CONFIGPROXY_AUTH_TOKEN:  <set to the key 'proxy.token' in secret 'hub-secret'>  Optional: false
    Mounts:
      /etc/jupyterhub/config/ from config (rw)
      /etc/jupyterhub/custom from custom-templates (rw)
      /etc/jupyterhub/secret/ from secret (rw)
      /srv/jupyterhub from hub-db-dir (rw)
      /usr/local/share/jupyterhub/static/external from custom-images (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from hub-token-79zrt (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      hub-config
    Optional:  false
  secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hub-secret
    Optional:    false
  custom-templates:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  custom-images:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  hub-db-dir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  hub-db-dir
    ReadOnly:   false
  hub-token-79zrt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hub-token-79zrt
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason      Age                   From              Message
  ----     ------      ----                  ----              -------
  Normal   Killing     19m                   kubelet, chick11  Stopping container hub
  Warning  FailedSync  3m55s (x65 over 17m)  kubelet, chick11  error determining status: rpc error: code = Unknown desc = unable to inspect docker image "sha256:a1d22e4b51ad5cd7375dfd78ccda141c41386ade6df2dc97b6ef5cd2260f1725" while inspecting docker container "faf8f17d08c2434d11ffc94551f118aca204374e75cd0ce4e88848f1750de682": no such image: "sha256:a1d22e4b51ad5cd7375dfd78ccda141c41386ade6df2dc97b6ef5cd2260f1725"
```
kubectl logs for the hub:
```
[I 2019-11-25 19:21:28.222 JupyterHub log:174] 302 GET /hub/api/oauth2/authorize?client_id=jupyterhub-user-lnpoirier%2540ucdavis.edu&redirect_uri=%2Fuser%2Flnpoirier%40ucdavis.edu%2Foauth_callback&response_type=code&state=[secret] -> /user/lnpoirier@ucdavis.edu/oauth_callback?code=[secret]&state=[secret] (lnpoirier@ucdavis.edu@10.0.0.116) 55.76ms
[I 2019-11-25 19:21:28.328 JupyterHub log:174] 200 POST /hub/api/oauth2/token (lnpoirier@ucdavis.edu@10.244.220.110) 73.67ms
[I 2019-11-25 19:21:28.405 JupyterHub log:174] 200 GET /hub/api/authorizations/token/[secret] (lnpoirier@ucdavis.edu@10.244.220.110) 67.41ms
[I 2019-11-25 19:21:31.678 JupyterHub log:174] 200 GET /hub/health (@10.0.0.111) 1.52ms
[I 2019-11-25 19:21:32.911 JupyterHub proxy:319] Checking routes
[C 2019-11-25 19:21:35.608 JupyterHub app:2448] Received signal SIGTERM, initiating shutdown...
[I 2019-11-25 19:21:35.609 JupyterHub app:2150] Cleaning up 1 services...
[I 2019-11-25 19:21:35.766 JupyterHub app:2162] Leaving single-user servers running
[I 2019-11-25 19:21:35.767 JupyterHub app:2170] I didn't start the proxy, I can't clean it up
[I 2019-11-25 19:21:35.767 JupyterHub app:2187] ...done
```
Logs for a terminating user pod: 
```
[I 2019-11-22 23:08:38.498 SingleUserLabApp log:174] 200 GET /user/tkumar@ucdavis.edu/api/terminals?1574464118700 (tkumar@ucdavis.edu@10.0.0.109) 3.26ms
[I 2019-11-22 23:08:38.504 SingleUserLabApp log:174] 200 GET /user/tkumar@ucdavis.edu/api/sessions?1574464118720 (tkumar@ucdavis.edu@10.0.0.109) 1.94ms
[I 2019-11-22 23:08:40.447 SingleUserLabApp log:174] 200 GET /user/tkumar@ucdavis.edu/api/contents/?content=1&1574464120658 (tkumar@ucdavis.edu@10.0.0.109) 5.98ms
[I 2019-11-22 23:08:44.150 SingleUserLabApp log:174] 200 GET /user/tkumar@ucdavis.edu/metrics?1574464124343 (tkumar@ucdavis.edu@10.0.0.109) 22.80ms
[I 2019-11-22 23:08:46.852 SingleUserLabApp log:174] 200 GET /user/tkumar@ucdavis.edu/api/contents/?content=1&1574464127062 (tkumar@ucdavis.edu@10.0.0.109) 5.56ms
[I 2019-11-22 23:08:48.531 SingleUserLabApp log:174] 200 GET /user/tkumar@ucdavis.edu/api/terminals?1574464128743 (tkumar@ucdavis.edu@10.0.0.109) 4.67ms
[I 2019-11-22 23:08:48.533 SingleUserLabApp log:174] 200 GET /user/tkumar@ucdavis.edu/api/sessions?1574464128744 (tkumar@ucdavis.edu@10.0.0.109) 3.89ms
[I 2019-11-22 23:10:30.484 SingleUserLabApp log:174] 200 GET /user/tkumar@ucdavis.edu/api/contents/Untitled.ipynb?content=0&1574464230695 (tkumar@ucdavis.edu@10.0.0.109) 4.03ms
[I 2019-11-22 23:10:30.504 SingleUserLabApp handlers:164] Saving file at /Untitled.ipynb
[I 2019-11-22 23:10:30.532 SingleUserLabApp log:174] 200 PUT /user/tkumar@ucdavis.edu/api/contents/Untitled.ipynb?1574464230718 (tkumar@ucdavis.edu@10.0.0.109) 30.44ms
[I 2019-11-22 23:10:30.555 SingleUserLabApp log:174] 200 GET /user/tkumar@ucdavis.edu/api/contents/Untitled.ipynb/checkpoints?1574464230767 (tkumar@ucdavis.edu@10.0.0.109) 3.59ms
[I 2019-11-22 23:16:48.830 SingleUserLabApp kernelmanager:217] Starting buffering for 1157f694-041f-4d4f-8471-135fd95f7e63:65911a47-ef9d-455e-a595-7f8886c5a37a
Websocket closed
[C 2019-11-23 00:22:07.720 SingleUserLabApp notebookapp:1560] received signal 15, stopping
[I 2019-11-23 00:22:07.722 SingleUserLabApp notebookapp:1694] Shutting down 1 kernel
[I 2019-11-23 00:22:08.024 SingleUserLabApp multikernelmanager:138] Kernel shutdown: 1157f694-041f-4d4f-8471-135fd95f7e63
```

**Comment by celine168** [comment] 2019-11-26 23:32
```
$ kubectl describe node chick2
Name:               chick2
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=chick2
                    kubernetes.io/os=linux
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: 10.0.0.102/24
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 12 Jun 2019 13:35:06 -0700
Taints:             <none>
Unschedulable:      false
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  ReadonlyFilesystem   False   Tue, 26 Nov 2019 15:30:14 -0800   Fri, 01 Nov 2019 15:55:18 -0700   FilesystemIsNotReadOnly      Filesystem is not read-only
  KernelDeadlock       False   Tue, 26 Nov 2019 15:30:14 -0800   Fri, 01 Nov 2019 15:55:18 -0700   KernelHasNoDeadlock          kernel has no deadlock
  NetworkUnavailable   False   Fri, 01 Nov 2019 14:16:41 -0700   Fri, 01 Nov 2019 14:16:41 -0700   CalicoIsUp                   Calico is running on this node
  MemoryPressure       False   Tue, 26 Nov 2019 15:31:07 -0800   Fri, 01 Nov 2019 14:15:46 -0700   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Tue, 26 Nov 2019 15:31:07 -0800   Fri, 01 Nov 2019 14:15:46 -0700   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Tue, 26 Nov 2019 15:31:07 -0800   Fri, 01 Nov 2019 14:15:46 -0700   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Tue, 26 Nov 2019 15:31:07 -0800   Fri, 01 Nov 2019 14:15:46 -0700   KubeletReady                 kubelet is posting ready status. AppArmor enabled
Addresses:
  InternalIP:  10.0.0.102
  Hostname:    chick2
Capacity:
 cpu:                6
 ephemeral-storage:  1920231720Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             65953048Ki
 pods:               110
Allocatable:
 cpu:                6
 ephemeral-storage:  1769685550222
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             65850648Ki
 pods:               110
System Info:
 Machine ID:                 1f26818c62694af4876a36dee58fbb5a
 System UUID:                49434D53-0200-9053-2500-539025006A4D
 Boot ID:                    0a2504d2-1aa0-4bd5-b426-c8e6536872eb
 Kernel Version:             4.15.0-51-generic
 OS Image:                   Ubuntu 18.04.2 LTS
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.5
 Kubelet Version:            v1.14.0
 Kube-Proxy Version:         v1.14.0
PodCIDR:                     10.244.2.0/24
Non-terminated Pods:         (20 in total)
  Namespace                  Name                                                  CPU Requests  CPU Limits  Memory Requests  Memory Limits     AGE
  ---------                  ----                                                  ------------  ----------  ---------------  -------------     ---
  binderhub                  binderhub-image-cleaner-47dvq                         0 (0%)        0 (0%)      0 (0%)           0 (0%)            129d
  binderhub                  hub-644db7d545-mshwc                                  200m (3%)     0 (0%)      512Mi (0%)       0 (0%)            17d
  default                    tinseled-penguin-node-problem-detector-tz8pc          0 (0%)        0 (0%)      0 (0%)           0 (0%)            25d
  jhub                       continuous-image-puller-s4q4p                         0 (0%)        0 (0%)      0 (0%)           0 (0%)            28h
  jhub                       jupyter-agkamath-40ucdavis-2eedu                      500m (8%)     4 (66%)     1073741824 (1%)  8589934592 (12%)  110m
  jhub                       jupyter-celine168-40gmail-2ecom                       500m (8%)     4 (66%)     1073741824 (1%)  8589934592 (12%)  100s
  jhub                       jupyter-glvandergaag-40ucdavis-2eedu                  500m (8%)     4 (66%)     1073741824 (1%)  8589934592 (12%)  116m
  jhub                       jupyter-haohua-40ucdavis-2eedu                        500m (8%)     4 (66%)     1073741824 (1%)  8589934592 (12%)  3m9s
  jhub                       jupyter-jdekarske-40ucdavis-2eedu                     500m (8%)     4 (66%)     1073741824 (1%)  8589934592 (12%)  5h21m
  jhub                       jupyter-jgeliahu-40ucdavis-2eedu                      500m (8%)     4 (66%)     1073741824 (1%)  8589934592 (12%)  79m
  jhub                       jupyter-nkgray-40ucdavis-2eedu                        500m (8%)     4 (66%)     1073741824 (1%)  8589934592 (12%)  75s
  jhub                       jupyter-sonroberts-40ucdavis-2eedu                    500m (8%)     4 (66%)     1073741824 (1%)  8589934592 (12%)  126m
  jhub                       jupyter-wyzhou-40ucdavis-2eedu                        500m (8%)     4 (66%)     1073741824 (1%)  8589934592 (12%)  101m
  kube-system                calico-node-j65lv                                     250m (4%)     0 (0%)      0 (0%)           0 (0%)            167d
  kube-system                kube-proxy-jgd2b                                      0 (0%)        0 (0%)      0 (0%)           0 (0%)            134d
  metallb-system             speaker-kbpcv                                         100m (1%)     100m (1%)   100Mi (0%)       100Mi (0%)        165d
  monitoring                 alertmanager-prometheus-operator-alertmanager-0       100m (1%)     100m (1%)   225Mi (0%)       25Mi (0%)         5d
  monitoring                 prometheus-operator-prometheus-node-exporter-6b2x5    0 (0%)        0 (0%)      0 (0%)           0 (0%)            34d
  staging-jhub               continuous-image-puller-mtzxj                         0 (0%)        0 (0%)      0 (0%)           0 (0%)            41h
  staging-jhub               user-scheduler-79dfc5c57f-vtf9f                       50m (0%)      0 (0%)      256Mi (0%)       0 (0%)            5d
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests       Limits
  --------           --------       ------
  cpu                5200m (86%)    36200m (603%)
  memory             10309Mi (16%)  77440483328 (114%)
  ephemeral-storage  0 (0%)         0 (0%)
Events:              <none>
```

**Comment by narrator0** [comment] 2019-12-01 04:17
After ssh in multiple nodes. Every node that we're drained have the following log message from kubelet.

```
Nov 30 20:03:16 chick6 kubelet[1034]: E1130 20:03:16.120277
1034 kubelet_volumes.go:154]
Orphaned pod "0158aae5-e607-11e9-8527-00259051cf1c" found,
but volume paths are still present on disk.
There were a total of 18 errors similar to this. Turn up verbosity to see them.
```

It maybe caused because some pods have been removed from the API however, the volume they used on disk have not been cleaned. This aligns to the message appears on webpage `Unable to mount volumes for pod`. This seemed to be an unsolved issue of Kubernetes. It seems like the only way to fix this is to manually unmount the volumes or reboot the system.

**Comment by lux12337** [comment] 2019-12-02 20:49
Restarting chicks to hopefully flush the orphan pods.
* [ ] Chick7
* [ ] Chick 10
* [ ] Chick 13

**Comment by lux12337** [comment] 2019-12-17 22:04
Add back problematic node and test for functionality

**Comment by lux12337** [comment] 2019-12-18 22:08
chick7 and chick10 have been added back to the cluster

**Comment by lux12337** [comment] 2019-12-18 23:15
It looks like that the problem is that the k8 API doesn't recognize that containers that successfully terminated actually terminated. It seems to be a common problem with no clear solution yet as discussed [here](https://github.com/kubernetes/kubernetes/issues/51835).

**Comment by celine168** [comment] 2019-12-19 00:58
To add to this, the Docker containers for some of the Terminating pods were already deleted, but the K8s API didn't seem to know this, so they continued to remain in a Terminating state.

In some other cases, (not related to the ones Luigi and I just looked at), Docker containers seem to be zombies and K8s has trouble deleting them (I believe, because they like to stall).

**Comment by lux12337** [comment] 2019-12-23 19:38
Get in touch with Jupyter community/Berkeley and ask if others have this issue and how they deal with it.

**Comment by lux12337** [comment] 2019-12-28 06:25
Created a post on [Juypyter discourse](https://discourse.jupyter.org/t/pods-stuck-in-terminating-state-on-node/2964).

**Comment by rkevin-arch** [comment] 2020-08-20 14:00
Not sure what the problem is, but we haven't experienced anything like this in a while. Looking at some of the logs, I see the following:
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests       Limits
  --------           --------       ------
  cpu                5200m (86%)    36200m (603%)
  memory             10309Mi (16%)  77440483328 (114%)
  ephemeral-storage  0 (0%)         0 (0%)
```
Maybe the nodes are resource starved enough to flip the heck out, causing some pods to be terminated incorrectly (terminated in docker but not labelled as such in kubernetes), even though that shouldn't happen and k8s should be able to deal with it. I'm going to tentatively close this issue until we see it again.

**Closed by rkevin-arch** 2020-08-20 14:00 UTC
Labels: high priority

**Comment by moorepants** [comment] 2020-08-24 08:27
Wait till we get some users :)
