### ISSUE TITLE
thebe persitent kernel may not respect different kernels on different pages

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/metalc#217] opened 2021-01-14 21:50 UTC
Go to:

https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/5.2.04%3A_How_to_Incorporate_Data_Files_in_Your_Code_Blocks-_For_Python

Run the cells

Navigate to the next page:

https://chem.libretexts.org/Courses/Remixer_University/LibreTexts_Construction_Guide/05%3A_Interactive_Elements/5.02%3A_Jupyter_Notebooks_(Executable_Programming_Code_and_Figures)/5.2.05%3A_How_to_Incorporate_Data_Files_in_Your_Code_Blocks-_For_R

Run the first cell and you get:

![image](https://user-images.githubusercontent.com/276007/104653354-c2f9f900-56ba-11eb-95b5-a7e763aa0be1.png)

It loads the kernel form the prior page but doesn't switch it to R!

This is likley a bug in our plugin as well as thebe. The persistent kernel needs to be aware that different kernels on the same binder instance can be on each page, right?

**Comment by rkevin-arch** [comment] 2021-01-14 22:31
The kernel is not persisted at all, iirc. I can actually run the second page in incognito mode and still get the same error without the first page. The problem is the code cell identifies itself as a python code cell to thebe, so the problem is almost certainly with ckeditor-binder-plugin and not thebe's binder session persistence.

**Comment by moorepants** [comment] 2021-01-14 22:34
Thanks. I've ran all the pages in the past when Tannavee created them and the worked, so the persistency thing was the only thing I could think of that changed.

**Comment by sandertyu** [comment] 2021-01-15 00:59
I don't understand why the issue would be with CKEditor. I cannot get the code cells on that page to run properly at all, even after deleting my kubernetes pod which is serving my session. Looking at the HTML source, the code cell is marked as an r cell
![r-cell](https://cdn.discordapp.com/attachments/763198235237154837/799442023689093180/unknown.png)

I'll probably try making some bare Thebe pages to see what works.

**Comment by sandertyu** [comment] 2021-01-15 01:17
I made a [barebone Thebe html page](https://github.com/LibreTexts/widget-testing/blob/master/Thebe/r_test.html) in the widget-testing repo in an attempt to replicate the setup on that page. We get the same error, even testing with Thebe version 0.5.0 and 0.5.1. This seems to imply the issue is with Thebe, or the code itself.

**Comment by rkevin-arch** [comment] 2021-01-15 02:21
bisected the commit that introduced the problem in thebe: 11ff270ab85d4b092c86f2e5ef16680bfdb072b2

**Comment by rkevin-arch** [comment] 2021-01-15 02:31
Found the issue, hotfix coming to ckeditor-binder-plugin

**Comment by rkevin-arch** [comment] 2021-01-15 03:25
The issue has been resolved in the master branch of ckeditor-binder-plugin and has been pushed, and it might take a while to show up in production. This issue is caused by https://github.com/executablebooks/thebe/issues/349.

**Comment by sandertyu** [comment] 2021-01-15 07:54
Everything works properly now. The issue was that the `kernelName` option in Thebe's binder configuration was outdated in Thebe 0.6.0, so all of those references needed to be changed to just `name`. Now Thebe will properly recognize the kernel specified in the HTML.

![R cell and console message](https://cdn.discordapp.com/attachments/763198235237154837/799546049252950036/unknown.png)

**Closed by sandertyu** 2021-01-15 07:54 UTC
Labels: high priority, libretexts page integration

**Comment by moorepants** [comment] 2021-01-15 08:56
Thanks guys. Thebe needs an enhanced test suite so things like this are caught.
