### ISSUE TITLE
Cluster Design Improvements 

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#34] opened 2019-08-14 01:42 UTC
### Nodes
* Create separate partitions for var and tmp, this prevents the root partition from crashing if var and tmp start taking up all the space.
  More info, taken from https://github.com/LibreTexts/metalc/issues/12#issuecomment-526273513:
Separating `/var` and `/tmp` to different partitions. This gives a limit since logs keep growing in size. However, doing this is a bit risky (all the files would need to be backed up first) and would require some downtime of rooster. We doubt that we will run out of space due to logs soon, but this would be worth considering for the staging cluster. More info [here](https://askubuntu.com/questions/540880/how-to-partition-my-disk-after-i-have-installed-ubuntu).
* Use two power supply units per node. Right now each node is only using one power supply, this is a point of failure.
* Add database nodes, Docker Postgres
* Use SSDs for the OS instead of HDDs.
### Network
I wanted to add some thoughts my dad mentioned.
* He thought that the fact that the Internet was connected to only rooster and not the rest of the cluster created a bottleneck for Internet speeds. He thinks that there should be a way to connect the Internet to the network switch so there wouldn't be a bottleneck.
  * Luigi and I thought that perhaps the other nodes were not connected to the Internet due to security, but we're not sure of the original reason.
* He also mentioned that the way we were configuring IPs (?) was weird? Will ask for clarification on this.
* Add ability to provision containers for different organizations on different networks (aka different VLANs). For example: somehow accessing the HPC network.
### Single Points of Failure
* Rooster, for the next iteration we can setup two HAproxy nodes to take over the role of rooster.
* One master, for the next iteration of the cluster. We should setup at least 3 master nodes, 2 master nodes is worst than 1.
* etcd storage. Setup a redundant etcd storage and frequently backup.
### GPU's
Some information about setting up different environments with different GPUs here: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/994
### Installation
* Use Puppet

**Comment by moorepants** [comment] 2019-08-14 18:17
All sounds like good things to investigate. I personally don't know how this is handled. I think the best bet is to see how others do this. Good question for Yuvi or others.

I'll try to get your dad on the payroll, but I think I can only hire undergrads :smile:

**Comment by lux12337** [comment] 2019-08-14 18:26
Maybe we can hire him as a consultant

**Comment by rkevin-arch** [comment] 2020-08-20 14:18
Are these meant for the galaxy cluster? I see it's labelled as such, but the issue is worded like it's meant for the flock cluster.

Some thoughts:
- /tmp should be mounted as tmpfs, just like /dev/shm. There's no reason why we need it to persist across reboots, and this would save some disk write cycles anyway. I'm down for mounting /var in its separate partition, but keep in mind /var/lib/docker would be in that partition and docker would fail if it is full. IMO we should still just have one partition, and make sure there is always enough disk space.
- Not sure what "database nodes" refer to. Nodes that specifically have postgres instances scheduled on them? We aren't even using postgres, although we could and that might make our JupyterHub a bit more robust.
- The "rooster is a bottleneck" thing has come up quite a bit recently, from it crashing due to "overheating" to the hen backup traffic overwhelming it and causing downtime. For the galaxy cluster, hopefully our metallb setup eliminates the need for a rooster entirely.
- We need to put more hours researching multus to deal with the VLAN thing.
- Re: `setup two HAproxy nodes to take over the role of rooster`, we don't need HAProxy for proxying services and can just let metallb handle everything. We do need HAProxy for the master nodes to load balance the kubernetes API endpoint, but that's it, and I plan on having one of these on every master node, and they will be exposed under a single VIP using keepalived.
- We definitely want 3 or 5 control plane nodes. If we can have ~20 or more nodes for our new cluster, I'd say 5 should be control plane nodes. If we have 3, we can tolerate at most 1 failed control plane node.
- Adding GPUs should be fairly easy, and we can just have a JupyterHub kubespawner profile with `nvidia.com/gpu: "1"` as an extra resource limit.

**Comment by moorepants** [comment] 2020-08-20 14:39
This may have been for flock and I mislabeled. I suggest looking through this and for anything that should be done on galaxy that info is added to the design docs or an issue that is clearly explained. This can closed after that.

**Comment by rkevin-arch** [comment] 2020-08-20 14:51
I see a lot of issues (such as #14 and #16) about the new cluster. Should I also consolidate them into a central "Galaxy design choices" issue and close them?

**Comment by moorepants** [comment] 2020-08-20 15:41
I'm fine with that as long as the issue text is organized nicely. We can break things off into separate issues in the future when the problem gets more detailed, etc.

**Comment by moorepants** [comment] 2021-01-08 10:25
I think all of this is addressed and remaining issues are in #14. So closing. The GPU thing can be a separate issue.

**Closed by moorepants** 2021-01-08 10:25 UTC
Labels: enhancement, galaxy cluster

**Comment by moorepants** [comment] 2021-01-08 10:26
GPU is here: https://github.com/LibreTexts/metalc/issues/72
