### ISSUE TITLE
CI/CD for default-env

### ISSUE THREAD

**Issue by celine168** [LibreTexts/metalc#111] opened 2019-12-17 22:14 UTC
I've been testing out both DockerHub and Travis CI's in a fork of default-env: https://github.com/celine168/default-env

They both work fairly similarly, I think with Travis CI; we can test the Dockerfiles more thoroughly. I also want to get it working so that whenever there is a pull request to the default-env, then a Docker image **with the tag of the corresponding SHA commit** automatically starts building. These two tasks haven't been done yet. 

Right now, all that DockerHub and Travis CI tests is whether the Docker container can build and run.

**Comment by Miniland1333** [comment] 2019-12-31 02:45
Since @narrator0 has been testing out Github Actions for the ckeditor-plugin, I would recommend considering using it for the CI. If it does not have the features you need, then Travis CI may be a better alternative.

**Comment by moorepants** [comment] 2021-01-08 10:35
duplicate of #123

**Closed by moorepants** 2021-01-08 10:35 UTC
